version: '3'
services:
  db:
    image: postgres:11-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - db-data:/var/pg-data
    networks:
      - backend
    environment:
      POSTGRES_DB: api
      PG_DATA: /var/pg-data
  api:
    build: ./api
    depends_on:
      - db
    expose:
      - 8081
    networks:
      - backend
      - frontend
    environment:
      - PORT=8081
      - NODE_ENV=production
      - DEBUG=api*
  dashboard:
    build: ./dashboard
    depends_on:
      - api
    networks:
      - frontend
    ports: 
      - "3000:3000"
    environment:
      - BROWSER=none

networks:
  frontend:
  backend:

volumes:
  db-data: